/**
 * Your Site API
 * Your Site API ⚡
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Scatter { 
    x: Array<any>;
    y: Array<any>;
    type: string;
    mode: string;
    marker?: object;
}

