"""empty message

Revision ID: d6a8dc21c57d
Revises: 54738a63b50d
Create Date: 2023-01-10 19:59:18.561837

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd6a8dc21c57d'
down_revision = '54738a63b50d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
