# name: Test Yaml File

# on:
#   push:
#     branches:
#       - test_CI_CD

# jobs:
#   skip:
#     if: true
#     steps:
#       - name: skip
#         uses: actions/checkout@v2
  

#   test:
#     name: Test gcloud Auth
#     permissions:
#       id-token: write
#       contents: read
#     runs-on: ubuntu-latest
#     steps:
#     - name: Github Action Manager
#       uses: actions/checkout@v2
#     - id: auth
#       name: Authenticate to Google Cloud 
#       uses: google-github-actions/auth@v0
#       with:
#         token_format: 'access_token'
#         workload_identity_provider: projects/662974556749/locations/global/workloadIdentityPools/github-actions-identity-pool/providers/github-action-stage
#         service_account: service_account@service_account.iam.gserviceaccount.com
#     - name: Access secret
#       run: |-
#         curl https://secretmanager.googleapis.com/v1/projects/662974556749/secrets/service_account \
#           --header "Authorization: Bearer ${{ steps.auth.outputs.access_token }}"
